version: '3'
services:
  test:
    build:
      context: ../../  
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache:/cache
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
#      MYSQL_PORT:
      MYSQL_USER: root 
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  builder:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache:/cache
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build123", "."]
  
  agent:
    image: bahms/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]

  db:
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  cache:
