version: '3'
services:
  test:
    build:
      context: ../../  
      dockerfile: docker/dev/Dockerfile
    volumes:
      - "/tmp/cache-pip:/cache"
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
#      MYSQL_PORT:
      MYSQL_USER: root 
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports
  
  agent:
    image: bahms/ansible
    volumes:
      - "../../ansible/probe.yml:/ansible/site.yml"
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"

  db:
    image: mysql:5.6
    hostname: db
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
